function url = scatter3_plotly(data, label, filename)

if size(data,2)~=3,
    error('data needs to be in 3D format.');
end

label_unique = unique(label, 'rows');

traces = cell(1, size(label_unique,1));

for i=1:size(label_unique,1),
    
    data_trace = data(ismember(label, label_unique(i,:), 'rows'),:);
    
    traces{i} = struct(...
    'x', data_trace(:,1), ...
    'y', data_trace(:,2), ...
    'z', data_trace(:,3), ...
    'mode', 'markers', ...
    'marker', struct(...
        'color', sprintf('rgb(%d,%d,%d)',floor(255*label_unique(i,1)),floor(255*label_unique(i,2)),floor(255*label_unique(i,3))), ...
        'size', 12, ...
        'symbol', 'circle', ...
            'line', struct(...
            'color', 'rgb(217, 217, 217)', ...
            'width', 1), ...
        'opacity', 0.9), ...
    'type', 'scatter3d');

end

layout = struct('margin', struct('l', 0, 'r', 0, 'b', 0, 't', 0));
response = plotly(traces, struct('layout', layout, 'filename', filename, 'fileopt', 'overwrite'));
url = response.url;

end